---
# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - pytest -v
