[tox]
envlist =
    3.11
    3.12
    3.13
    3.14
requires =
    tox>=4
    tox-uv-bare>=1.36.0

[testenv]
description = run unit tests
runner = uv-venv-lock-runner
extras =
    dev
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest --basetemp="{envtmpdir}" {posargs}
