"""Console script for jenkins_jobs to report jobs at a Jenkins server."""

import argparse
import sys

from jenkins_jobs.retrievers import RESTRetriever, FileSystemRetriever
from jenkins_jobs.exceptions import NoSchemaSuppliedRESTError
from jenkins_jobs.formatters import FORMATTERS

HTML_REPORT_FILENAME = "report.html"
CSV_REPORT_FILENAME = "report.csv"


def main():  # pragma: no cover
    """Console script for jenkins_jobs."""
    parser = argparse.ArgumentParser(description="Extracts Jenkins job information and generates a report")
    parser.add_argument("--format", choices=sorted(FORMATTERS), default="csv", help="report output format (default: csv)")

    rest_group = parser.add_argument_group(
        "Jenkins REST connection",
        "--user, --token and --jenkins are required together, to connect to "
        "a live Jenkins server. None of them can be combined with "
        "--shelve-file.",
    )
    rest_group.add_argument("--user", help="Jenkins user for REST interface")
    rest_group.add_argument("--token", help="Jenkins token for REST interface")
    rest_group.add_argument("--jenkins", help="Jenkins http[s]://FQDN|IP:port")

    file_group = parser.add_argument_group(
        "Local shelve file",
        "Reads a previously exported snapshot instead of connecting to a "
        "Jenkins server. Cannot be combined with --user/--token/--jenkins.",
    )
    file_group.add_argument("--shelve-file", help="path to a shelve file previously generated by jenkins_exporter")

    args = parser.parse_args()
    rest_options = (args.user, args.token, args.jenkins)

    if args.shelve_file:
        if any(rest_options):
            parser.error("--shelve-file cannot be combined with --user/--token/--jenkins")

        jobs_retriever = FileSystemRetriever(args.shelve_file)
    else:
        if not all(rest_options):
            parser.error("--user, --token and --jenkins are all required when --shelve-file is not given")

        if not args.jenkins.startswith("http"):
            raise NoSchemaSuppliedRESTError

        jobs_retriever = RESTRetriever(user=args.user, token=args.token, jenkins_server=args.jenkins)

    jobs = jobs_retriever.all_jobs()
    formatter = FORMATTERS[args.format]()
    content = formatter.generate(jobs())

    if args.format == "html":
        with open(HTML_REPORT_FILENAME, "w") as fp:
            fp.write(content)

        print(f"HTML report written to {HTML_REPORT_FILENAME}")
    else:
        with open(CSV_REPORT_FILENAME, "w") as fp:
            fp.write(content)

        print(f"CSV report written to {CSV_REPORT_FILENAME}")


if __name__ == "__main__":
    sys.exit(main())  # pragma: no cover
